spring:
  application:
    name: service-admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://username:password@localhost:8761/eureka
server:
  port: 8083