spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # 라우팅 규칙의 고유 식별자
        - id: first_route
          # 대상 서비스 (백엔드 서비스의 주소)
          uri: lb://service-admin
          filters:
            - name: CustomRouteFilter
              # 인자 값 넣기
              args:
                headerName: X-Dynamic-Header
                headerValue: DynamicValue
                pre: true
                post: false
          predicates:
            # /admin/** 경로로 들어오는 요청을 이 서비스로 라우팅
            - Path=/admin/**
        - id: second_route
          uri: lb://service-user  # 다른 백엔드 서비스
          predicates:
            - Path=/users/**  # /user/** 경로로 들어오는 요청을 이 서비스로 라우팅
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://username:password@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true
