spring:
  application:
    name: service-admin
#  profiles:
#    active: 해당 config client 환경 (dev/prod)
  config:
    import:
      - "optional:configserver: http://username:password@localhost:9000"

# config repository에서 관리
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://username:password@localhost:8761/eureka
