server:
  port: 9000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ngs1214/Spring-MSA-config.git
          # 로컬 SSH 설정을 무시하고 private-key 속성에 지정된 개인 키만 사용
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKQIBAAKCAgEAsM35oP4UitDAreeWRQLEJbwZtgAl0SFRRWINuOLFuqaGppkq
            8x5+Xf2g9kQg138qdlgsjFQEr28WN96gB5JNLaiYRoYsnQ+u241DgzA9yJdT2uW2
            kOKkAczSD/OnafpS6KgQEYQXgMGePJKTvG664FC4B4Bwyu9tqqiYCPLgpy9wUZxF
            y2Jivd/GuXNTCFUa5O4l3Vvvn2IF1QztLFrkMz6BBP8OLIirNfugFyz3XX2VK3Xm
            YWjUr3nIifNLOCpIgUcxGjTgeupc3gHtRHjKYO1l6erfCEYz4tGAol9Au8wGInEi
            D9PAjz6y9OUqig10wU5fui2sjSiN1DI/9SnVvwgpSUfwoggP0V9y6p+gs1UCnpGt
            MKHeaL5wJ3GO9jAn8KWtlxqdEbKaJFIbeFCdzWYuLxEtk2O13V84hrSjnP3btZQU
            maNjGsM/ZgPg30Ac5XRfJv6rA2w1GVMCYrfERj6pk3m1zrqYD7o0sOjErFp6/Myw
            QvDWu4Ec/zyglc4ChvWE4neHRHvUSOBcINjyR9Z3mYpQG0QeExyFRGqFOs4abIFY
            HwdfBIX2V1C6FYH3ZPukTTLvtQOpvscpMP0pkitt+6SoyZNPrlN+MTDuYJJ1XszW
            FDhGnxS7dz9aCgnLv51QKwMVpOya503V/ZCc39h90U4xkJgQ4tJmQ7NiD0kCAwEA
            AQKCAgARzXuwSUU6QRDVsfcAlem4Pvt7xwIHz8oGKXxmPHdadwAh8FRRzKU+w5Yc
            lfmUmVpmNjSuIJukKpRbJdCJUqLw0QQcPdBqNDUQKGY+5HGkLBCmfvDmH9wRzlTs
            hEU8N5d3k8yiZuGS9mv/f2be12t7wMT3BGjXFkq9n2JHrGUQkIdHwGuKsiptIgY5
            kDIxKZieqpgndOVo8A7USAvtpm1J96Y4IZKEy3Ip6l9RVhbGVCncCXAcKNkZnjKi
            KVxOmHtagRehoudjmQum0xzYAy2lmuHjLuIsTB1XXm8ManjzL/UCLNAYNeMyyUZt
            wFGLOxWhjUm4TncMc6PsVO75ua+q9KvBvcMTkqMQ4ooL4IIPlh3QXTfAk6b4JKL5
            /LwUD8WRE8TZpOf2Z8vJUkT3Dptr1PJ4eePAFESyUXSCwIk5NfARJ8K3YHc/cVuU
            4md/be4rFqZow9Y8NDlPmdJU6pIGEsYyyy3C+k2UX6IlvpLRq1cv6/+LDyeve3Vq
            ul5bHAefdZ4HcTaTl/QASyCMDKfh0rZavpcur3J/IXd5yGVL+aJhu8hcg3GWvgkU
            gNdDe9hVo46+I3dVvdcQuTkUk0TM/sXHuH5wibeegFnhQzzF67rSG262YpYX47u1
            DCPppzIbhOR2eho/8Gtn2JgPwOU2dh5Jg9h3aexcuV21zqdjgQKCAQEA5KQXnF2r
            n+Ri3fWj7jVJMD4k/CJUa439663OwoXpOMC64sw2W8RONqVNxVIxON3Aeh1iY4eq
            Xvm08J7XJZOENuk5mxrzYCTDlXkMnEUeFxtqmmrJVSt/4YbBUurcr9/35/uC9Nmr
            2QTj7LHRfauP7ptwArQ4OCPyxSXMql8EqLgqbrLtQw+rOpYK0+6Une4WAEqKMAUH
            UzSuG6/RknQ6KERxO31Dm/jofRinUy2JR9FOzNaZ2TrIV/CuptKiuQTLlWZMHknb
            mLutfR47H7jJN3kWZBW1JoXfx0mANh6ICVaPTGLmCxi0EOSKA8g7Tekz0scLqVS2
            3P/fquPFzp2MGQKCAQEAxfX9guLxODwNzuyjChrCPMPpxkNLL3caQ5EXywDLpL+C
            rR6x32jyqrIH2soUZ+sYMmMQjaxZ6Fi+3ktQeTkSpDdNAAB4yhD+gvcGqH7cEQIP
            oerEiJnabAOUl1AEdqZ7iolh5MZ7t2Jrfm3o0Thejvy2ckD55Y3J+FUmFoohrR4o
            B4TVYnnRQKNePg0jcNNzfcwE4WouBluKyjBLPZYqx84rcsY/Arq2I1SH14pI/kwM
            BeZsizBvjdv0nEDC7z+SbM0MlJoWvraZTEsHDekVdFPsnQN93CkBpYXMDvm4vE5x
            4KiNJFcEsdcscqylAwD5XT4PYsJESDTy8vdU87wCsQKCAQEAmnztnzADmQP+ca9a
            VsgWbcxvvRWNKSdGHQrRm8pTrY88N6Z4TEU1++JxzBQfQidDuL9GDa5LReU/hx4s
            jS1BtsCbtdvd+mac6NBj3ussy7wwqanh4/SCceZVlisvdn7EyTC+aabyYK7XOsVj
            oaBcnoLUil8vZW+Ux/UkdzHAuifGNAoeGqPptKpRIqYgMR4AK64x9QRQ0L3Vrst7
            tZNnAHJOeD3JgwgKPwx7cs5f5fDdZ7bROWBoolL0D7BfVtiQnqACaqzI/khBjzrw
            BB0diKf+ox2vyxnF/KgDQ44ZqQWdyaVBftnwQUHKp4eR2rDp3U+053NgI6+Yd6Vz
            sInvcQKCAQBIBeuqRy9EKnVLp8TZ1Ep/GThgrfMY3dhsZMmnTi7JTfQZUGWexuwj
            NoqtC4DJHju7eVd4dBBx/HfVIMmykRU7MfON4J4RxoUS2RVPEHi4p2tQmb3PhUp2
            qgbR1ocJNCEWkk1PkvdIDULWyN4/4KZml4M5pnJFFoU5GKG26aK+/Y3KzoVkQrXj
            Mo0DPnx6fDQ0vJm5+YutPHkOfuuhCJWgBF7Cb2ZVc+D4kbSqsuFDxB9Ltj4flgvA
            LRqeDuHdcd+wPhopprZHxN+ZZmK2qOrpW+9mYPLVuwWiVz+a4zhXKqM7/Zb8dbx7
            h7HgNvgCU8RmLEIkyFFXhAwwYdRCqVDBAoIBAQDTwbCWZkOBsvy2N8cpCSemTR/E
            TEhH0X7NicR7QsdccHKo1HjaMpE9LIZVZFwbJE0GnzDtUxpqNGK93iSNC4u6LuDG
            HKXiwGy0djVBdROb8u/mACAVNQKbtlm4jjDe8p8y8DSBuyhQNseyB3qffW+m2v2O
            PhPwcx508Hn/VW50nYvhRX40XYumpekT6s9GeHxeQ6ZnZjcuLK/biFfuznLXoqpc
            yZixkkJjZVobWG2ZF/RmaizW2f8K1Bux6qZOQp9KVkjihWGPxSXJVnuFoZvIQR/0
            5X9wUZzZmB/moYGuOLiGOHEDKvfP8AADZrWCbwjh7yBrrW6W0iEJZt4t7MVJ
            -----END RSA PRIVATE KEY-----
